AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Combined CloudFormation template for TRE Egress application setup in RG.
  Creates egressstore and egressnotification buckets, Lambda function, and all required resources.
  Lambda permissions are restricted to only the created buckets and KMS key.

Parameters:
  LambdaFunctionName:
    Type: String
    Description: Name of the Lambda function
    AllowedPattern: ^[a-zA-Z0-9\-_.]{3,63}
    Default: rg-EgressLambda
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket containing the Lambda zip file
  S3ObjectKey:
    Type: String
    Description: Key of the Lambda zip file in the S3 bucket
    Default: egress-copy.zip

Resources:
  EgressStoreEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Master key used to encrypt objects stored in the egress-store bucket
      EnableKeyRotation: true
      KeyPolicy:
        Version: "2012-10-17"
        Id: egress-store-kms-policy
        Statement:
          - Sid: Allow root
            Effect: Allow
            Principal:
              AWS:
                - !Sub "arn:aws:iam::${AWS::AccountId}:root"
            Action:
              - "kms:*"
            Resource: "*"

  EgressStoreEncryptionKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::AccountId}-rg/s3/egressstorever"
      TargetKeyId: !Ref EgressStoreEncryptionKey

  EgressStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-rg-egress-storever"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt EgressStoreEncryptionKey.Arn
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "https://d2bit1tve2oue7.cloudfront.net"
            AllowedMethods:
              - POST
            ExposedHeaders:
              - ETag
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  EgressStoreBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EgressStoreBucket
      PolicyDocument:
        Version: "2012-10-17"
        Id: PutObjectPolicy
        Statement:
          - Sid: Deny requests that do not use TLS/HTTPS
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !Join ["/", [!GetAtt EgressStoreBucket.Arn, "*"]]
              - !GetAtt EgressStoreBucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: Deny requests that do not use SigV4
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource: !Join ["/", [!GetAtt EgressStoreBucket.Arn, "*"]]
            Condition:
              StringNotEquals:
                s3:signatureversion: "AWS4-HMAC-SHA256"

  EgressNotificationBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${AWS::AccountId}-rg-egress-notification-bucketver"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              KMSMasterKeyID: !GetAtt EgressStoreEncryptionKey.Arn
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
      VersioningConfiguration:
        Status: Enabled
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - "https://d2bit1tve2oue7.cloudfront.net"
            AllowedMethods:
              - POST
            ExposedHeaders:
              - ETag
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  EgressNotificationBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref EgressNotificationBucket
      PolicyDocument:
        Version: "2012-10-17"
        Id: PutObjectPolicy
        Statement:
          - Sid: Deny requests that do not use TLS/HTTPS
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource:
              - !Join ["/", [!GetAtt EgressNotificationBucket.Arn, "*"]]
              - !GetAtt EgressNotificationBucket.Arn
            Condition:
              Bool:
                aws:SecureTransport: false
          - Sid: Deny requests that do not use SigV4
            Effect: Deny
            Principal: "*"
            Action: s3:*
            Resource: !Join ["/", [!GetAtt EgressNotificationBucket.Arn, "*"]]
            Condition:
              StringNotEquals:
                s3:signatureversion: "AWS4-HMAC-SHA256"

  EgressNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: "rg-EgressTopicTest"
      KmsMasterKeyId: !Ref EgressStoreEncryptionKey
      TopicName: "EgressTopicTest"

  EgressStoreDb:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: "rg-EgressStorergv28"
      AttributeDefinitions:
        - AttributeName: "id"
          AttributeType: "S"
        - AttributeName: "workspaceId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "id"
          KeyType: "HASH"
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: "WorkspaceIdIndex"
          KeySchema:
            - AttributeName: "workspaceId"
              KeyType: "HASH"
          Projection:
            ProjectionType: "ALL"

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: EgressLambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: RGLambdaBasics
                Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"
              - Sid: AllowEgressLambdaToCopyFromStoreToNotification
                Effect: "Allow"
                Action:
                  - "s3:GetObject"
                  - "s3:PutObject"
                  - "s3:ListBucket"
                  - "s3:DeleteObject"
                  - "s3:GetBucketLocation"
                  - "s3:ListBucketMultipartUploads"
                  - "s3:AbortMultipartUpload"
                  - "s3:ListMultipartUploadParts"
                  - "s3:PutObjectAcl"
                  - "s3:GetObjectAcl"
                  - "s3:DeleteObjectVersion"
                  - "s3:GetObjectVersion"
                  - "s3:PutObjectVersionAcl"
                  - "s3:GetObjectVersionAcl"
                Resource:
                  - !GetAtt EgressStoreBucket.Arn
                  - !Join ["/", [!GetAtt EgressStoreBucket.Arn, "*"]]
                  - !GetAtt EgressNotificationBucket.Arn
                  - !Join ["/", [!GetAtt EgressNotificationBucket.Arn, "*"]]
              - Sid: AllowKMSForEgressBuckets
                Effect: "Allow"
                Action:
                  - "kms:Decrypt"
                  - "kms:Encrypt"
                  - "kms:GenerateDataKey"
                  - "kms:DescribeKey"
                Resource: !GetAtt EgressStoreEncryptionKey.Arn

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Runtime: nodejs18.x
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3ObjectKey
      Timeout: 900

  LambdaFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref LambdaFunction
      AuthType: AWS_IAM

  InvokeLambdaPermissionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: "InvokeLambda-${LambdaFunctionName}"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: "lambda:InvokeFunctionUrl"
            Resource: !GetAtt LambdaFunction.Arn
            Condition:
              StringEquals:
                lambda:FunctionUrlAuthType: "AWS_IAM"

Outputs:
  EgressStoreBucketArn:
    Description: ARN of the Egress Store S3 bucket
    Value: !GetAtt EgressStoreBucket.Arn

  EgressStoreKmsArn:
    Description: ARN of the Egress Store KMS Key
    Value: !GetAtt EgressStoreEncryptionKey.Arn

  EgressStoreBucketName:
    Description: Name of the Egress Store S3 bucket
    Value: !Ref EgressStoreBucket

  EgressNotificationBucketName:
    Description: Name of the Egress Notification S3 bucket
    Value: !Ref EgressNotificationBucket

  EgressStoreLambdaUrl:
    Description: Lambda Function Url
    Value: !GetAtt LambdaFunctionUrl.FunctionUrl

  EgressStoreLambdaArn:
    Description: ARN of the Lambda function
    Value: !GetAtt LambdaFunction.Arn

  EgressStoreDbTableName:
    Description: Name of the Egress Store DynamoDB table
    Value: !Ref EgressStoreDb

  EgressNotificationTopicArn:
    Description: ARN of the Egress Notification SNS Topic
    Value: !Ref EgressNotificationTopic
