AWSTemplateFormatVersion: '2010-09-09'
Description: >
  CloudFormation template to create a SageMaker Domain
  with an IAM execution role. Applies project_name tag.

Parameters:
  Namespace:
    Type: String
    Description: An environment name that will be prefixed to resource names
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC where SageMaker domain will be created.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet for the SageMaker domain.
  ProjectId:
    Description: Project Id that will be added as tag to the resources.
    Type: String
  

Resources:
  SageMakerExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${Namespace}-SageMakerExecutionRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      Tags:
        - Key: project_name
          Value: !Ref ProjectId
        - Key: cost_resource
          Value: !Ref "AWS::StackName"


  SageMakerDomain:
    Type: AWS::SageMaker::Domain
    Properties:
      AuthMode: IAM
      DomainName: !Sub "${Namespace}-sagemaker-domain"
      DefaultUserSettings:
        ExecutionRole: !GetAtt SageMakerExecutionRole.Arn
      SubnetIds:
        - !Ref SubnetId      
      VpcId: !Ref VpcId
      Tags:
        - Key: project_name
          Value: !Ref ProjectId
        - Key: cost_resource
          Value: !Ref "AWS::StackName"
          

Outputs:
  SageMakerDomainId:
    Description: ID of the created SageMaker Domain
    Value: !Ref SageMakerDomain

  SageMakerExecutionRoleArn:
    Description: IAM role created for SageMaker
    Value: !GetAtt SageMakerExecutionRole.Arn
