Metadata: 
  License: Apache-2.0
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template to create an EC2 instance with NICE-DCV and IGV  pre installed.'

Mappings: 
  RegionMap: 
    us-east-1: 
      AmiID: "ami-0d114a627f015307f"
    us-east-2: 
      AmiID: "ami-0684a90a3dafafa2b"
    us-west-1: 
      AmiID: "ami-01219e6d4eeb84011"
    us-west-2: 
      AmiID: "ami-005d3bea287ac9e7a"
    ap-south-1: 
      AmiID: "ami-03b63611f215b913b"
    ap-southeast-1: 
      AmiID: "ami-06802e4bc7a0376aa"
    ap-southeast-2: 
      AmiID: "ami-0be5eaf9b870eb48a"
    ap-east-1: 
      AmiID: "ami-0483a4200dfccea47"


Parameters:
  Namespace:
    Type: String
    Description: An environment name that will be prefixed to resource names
  S3Mounts:
    Type: String
    Description: A JSON array of objects with name, bucket, and prefix properties used to mount data
  IamPolicyDocument:
    Type: String
    Description: The IAM policy to be associated with the launched workstation
  EnvironmentInstanceFiles:
    Type: String
    Description: >-
      An S3 URI (starting with "s3://") that specifies the location of files to be copied to
      the environment instance, including any bootstrap scripts
  InstanceType:
    Description: Choose the instance type e.g t3.medium (2vCPU , 2GiB RAM), t3.large (2vCPU, 8GiB RAM), t3.xlarge(4vCPU, 16GiB RAM)
    Type: String
    Default: t3.medium
    AllowedValues:
      [
        t3.medium,
        t3.large,
        t3.xlarge,
      ]
    ConstraintDescription: must be a valid EC2 instance type.
  EBSVolumeSize:
    Description: The initial size of the volume (in GBs)  EBS will use for storage.
    Type: Number
    Default: 32
  KeyPair:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance. If no key pairs exist, please create one from the button next to the dropdown. Please contact your Administrator if you are unable to create one.
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  AllowedIpAddress:
    Description: The IP address range that can be used to SSH to instance and Connect to DCV
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.

Conditions:
  IamPolicyEmpty: !Equals [!Ref IamPolicyDocument, '{}']

Resources:
  SSMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Join ['-', [Ref: Namespace, 'SSM-Policy']]
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ssm:PutParameter
              - ssm:GetParameter
              - ssm:DescribeParameters
            Resource: "*"
  IAMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Join ['-', [Ref: Namespace, 'ec2-role']]
      Path: '/'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - !If
          - IamPolicyEmpty
          - !Ref 'AWS::NoValue'
          - PolicyName: !Join ['-', [Ref: Namespace, 's3-studydata-policy']]
            PolicyDocument: !Ref IamPolicyDocument
      ManagedPolicyArns:
        - Ref: SSMPolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: !Join ['-', [Ref: Namespace, 'ec2-profile']]
      Path: '/'
      Roles:
        - Ref: IAMRole

  EC2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        Timeout: PT10M
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          default:
            - config1
            - config2
        config1:
          files:
            "/home/ec2-user/.config/autostart/igv.desktop":
              mode: "000644"
              owner: "ec2-user"
              group: "ec2-user"
              content: |
                [Desktop Entry]
                Type=Application
                Exec="/home/ec2-user/start_igv.sh"
                Hidden=false
                NoDisplay=false
                X-GNOME-Autostart-enabled=true
                Terminal=true
                Name=igv
                Comment=igv Desktop
            "/home/ec2-user/.config/autostart/studymount.desktop":
              mode: "000644"
              owner: "ec2-user"
              group: "ec2-user"
              content: |
                [Desktop Entry]
                Type=Application
                Exec="/home/ec2-user/mount_study.sh"
                Hidden=false
                NoDisplay=false
                X-GNOME-Autostart-enabled=true
                Terminal=true
                Name=Study-Mounting
                Comment=Study Mounting
            "/home/ec2-user/mount_study.sh":
              mode: "000755"
              owner: "ec2-user"
              group: "ec2-user"
              content: !Sub |
                #!/bin/sh
                set -x
                # Adding sleep to avoid mounting failure
                sleep 30
                mount_s3.sh 2>&1 >> /home/ec2-user/mount_s3.log
            "/home/ec2-user/start_igv.sh":
              mode: "000755"
              owner: "ec2-user"
              group: "ec2-user"
              content: !Sub |
                #!/bin/sh
                set -x
                xhost +local:all
                # Adding sleep to wait for study mounting
                sleep 40
                docker run --rm -ti -v /home/ec2-user:/home/ec2-user --net=host -e DISPLAY=:1 relevancelab/igv-ide:1.1.0
            "/home/ec2-user/set_user_token.sh":
              mode: "000755"
              owner: "ec2-user"
              group: "ec2-user"
              content: !Sub |
                #!/bin/bash
                # trap '/opt/aws/bin/cfn-signal --exit-code 1 --resource EC2Instance --region ${AWS::Region} --stack ${AWS::StackName}' ERR
                # Get the session token
                TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")

                # Get the region to build the parameter name
                region=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/placement/region)
                echo "Retrieved region ${region} from metadata service"

                # Get the instance id to build the parameter name
                instance_id=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)

                session_id="rg-session"
                auth_token=`uuidgen`
                parameter_name="/RL/RG/igv-viewer/auth-token/$instance_id"
                aws ssm put-parameter --name "$parameter_name" --type "String" --value '{"auth_token":"'$auth_token'","session_id":"'$session_id'"}' --region $region --overwrite
                echo "User token set successfully"
            "/home/ec2-user/supervisor/supervisord.conf":
              mode: "000644"
              owner: "ec2-user"
              group: "ec2-user"
              content: |
                [unix_http_server]
                file=/home/ec2-user/supervisor/supervisor.sock   ; the path to the socket file

                [supervisord]
                logfile=/home/ec2-user/supervisor/supervisord.log ; main log file; default $CWD/supervisord.log
                logfile_maxbytes=50MB                  ; max main logfile bytes b4 rotation; default 50MB
                logfile_backups=10                     ; # of main logfile backups; 0 means none, default 10
                loglevel=info                          ; log level; default info; others: debug,warn,trace
                pidfile=/home/ec2-user/supervisor/supervisord.pid ; supervisord pidfile; default supervisord.pid
                nodaemon=false                         ; start in foreground if true; default false
                minfds=1024                            ; min. avail startup file descriptors; default 1024
                minprocs=200                           ; min. avail process descriptors;default 200

                [rpcinterface:supervisor]
                supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

                [supervisorctl]
                serverurl=unix:///home/ec2-user/supervisor/supervisor.sock ; use a unix:// URL  for a unix socket

                [program:dcv-custom-auth]
                command=docker run -p 8445:8445 -e PORT=8445 -e PARAMNAMEPREFIX=/RL/RG/igv-viewer/auth-token/ relevancelab/nice-dcv-auth-svc:1.0.0  ; the program (relative uses PATH, can take args)
                directory=/home/ec2-user                                                                                                            ; directory to cwd to before exec (def no cwd)
                user=ec2-user                                                                                                                       ; setuid to this UNIX account to run the program
                redirect_stderr=true                                                                                                                ; redirect proc stderr to stdout (default false)
                stdout_logfile=/home/ec2-user/supervisor/cust_auth.log
            "/home/ec2-user/supervisor/supervisord.log":
              content: "\n"
              mode: "000664"
              owner: "ec2-user"
              group: "ec2-user"
            "/home/ec2-user/supervisor/cust_auth.log":
              content: "\n"
              mode: "000664"
              owner: "ec2-user"
              group: "ec2-user"
            "/home/ec2-user/disable_lock.sh":
              content: !Sub |
                #!/bin/bash
                gsettings set org.gnome.desktop.lockdown disable-lock-screen 'true'
                echo "Lock disabled successfully"
              mode: "000755"
              owner: "ec2-user"
              group: "ec2-user"
        config2:
          commands:
            01_start_ext_auth:
              cwd: "/home/ec2-user/supervisor"
              command: "/usr/local/bin/supervisord"
            02_set_user_token:
              cwd: "/home/ec2-user"
              command: "/home/ec2-user/set_user_token.sh"
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/usr/bin/env bash
          exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1
          # trap '/opt/aws/bin/cfn-signal --exit-code 1 --resource EC2Instance --region ${AWS::Region} --stack ${AWS::StackName}' ERR

          # Install supervisor and start on boot
          pip3 install supervisor crudini

          # Route auth request to external authenticator and restart dcv
          /usr/local/bin/crudini --set /etc/dcv/dcv.conf security auth-token-verifier \"http://127.0.0.1:8445\"
          systemctl restart dcvserver

          # Create dcv session start script
          cat << EOF > /usr/local/bin/start-dcv-session
          dcv create-session rg-session --name rg-session --user ec2-user --owner ec2-user
          EOF

          # Create dcv session on reboot
          chown root: "/usr/local/bin/start-dcv-session"
          chmod 775 "/usr/local/bin/start-dcv-session"
          sh "/usr/local/bin/start-dcv-session"

          # Install Docker
          yum install -y docker
          systemctl enable docker.service
          systemctl enable containerd.service
          systemctl start docker
          usermod -a -G docker ec2-user

          # Pull docker image
          docker pull relevancelab/igv-ide:1.1.0
          docker pull relevancelab/nice-dcv-auth-svc:1.0.0

          # Run init script to create files
          /opt/aws/bin/cfn-init --verbose --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}

          # Add command to start on reboot
          crontab -l 2>/dev/null > "/tmp/crontab"
          sh "/usr/local/bin/start-dcv-session"
          echo '@reboot cd /home/ec2-user/supervisor && /usr/local/bin/supervisord 2>&1 >> /home/ec2-user/supervisor/cust_auth.log' >> "/tmp/crontab"
          echo '@reboot /usr/local/bin/start-dcv-session 2>&1 >> /var/log/start-dcv-session.log' >> "/tmp/crontab"
          echo '@reboot /home/ec2-user/set_user_token.sh 2>&1 >> /var/log/set_user_token.log' >> "/tmp/crontab"
          crontab "/tmp/crontab"
          # Restart DCV session to start igv
          dcv close-session rg-session
          sh "/usr/local/bin/start-dcv-session"

          # Remove password and lock for ec2-user
          passwd -l ec2-user
          dcv create-session lock-session --name lock-session --user ec2-user --owner ec2-user --init /home/ec2-user/disable_lock.sh

          # Download and execute bootstrap script
          aws s3 cp --region "${AWS::Region}" "${EnvironmentInstanceFiles}/get_bootstrap.sh" "/tmp"
          chmod 500 "/tmp/get_bootstrap.sh"
          /tmp/get_bootstrap.sh "${EnvironmentInstanceFiles}" '${S3Mounts}' "${AWS::Region}"

          /opt/aws/bin/cfn-signal -e $? --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}

      InstanceType: !Ref 'InstanceType'
      SecurityGroups: [!Ref 'InstanceSecurityGroup']
      KeyName: !Ref 'KeyPair'
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AmiID
      IamInstanceProfile: !Ref InstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref EBSVolumeSize
            Encrypted: true
      PropagateTagsToVolumeOnCreation: true
      Tags:
        - Key: Name
          Value: !Join ['-', [Ref: Namespace, 'ec2-linux']]
        - Key: Description
          Value: EC2 workspace instance
        - Key: cost_resource
          Value: !Sub ${AWS::StackName}


  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: !Ref 'AllowedIpAddress'
      - IpProtocol: tcp
        FromPort: '8443'
        ToPort: '8443'
        CidrIp: !Ref 'AllowedIpAddress'


Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
  InstanceIPAddress:
    Description: IP address of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicIp]
  InstanceDNSName:
    Description: DNS name of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, PublicDnsName]
  ApplicationPort:
    Description: The Port in which the application is running
    Value: '8443'
